### ISSUE TITLE
It is possible to configure a sort of dnsmaq?

### ISSUE THREAD

**Issue by simar88** [bakerface/wireless-tools#1]
Hi @bakerface  i found your module very interesting and i think that i'll test it in these day on a project with my new raspberry pi.
I would like to know if at the moment the module provide a a way to configure a sort of dnsmasq or if i have to use some other module that i found on npm.
Thanks in advance for the answer and for module developed.

**Comment by bakerface** [comment]
Great question @simar88. I have only added bindings to a few applications at this time. I would love to integrate more (specifically **dnsmasq**, **dhcpd**, and **dhcpcd**) into the project. I accept pull requests if you want to contribute.

**Comment by simar88** [comment]
Thanks @bakerface for the answer. I'll wait for this feature.
If i'll be able to helpe i'll do with pleasure.
At the moment i'm trying to undestrand how to use it and i have an issue that i'll open.
Maybe i'm forgetting something or i'm doing some mistake but i can't figure it out.
