### ISSUE TITLE
Hostapd

### ISSUE THREAD

**Issue by snowbreeze** [bakerface/wireless-tools#14]
I want to setup my rpi as a AP.
I did sudo apt-get install hostapd

installed wireless-tools

then ran 

```
var hostapd = require('wireless-tools/hostapd');
 
var options = {
  channel: 6,
  driver: 'rtl871xdrv',
  hw_mode: 'g',
  interface: 'wlan0',
  ssid: 'RaspberryPi',
  wpa: 2,
  wpa_passphrase: 'raspberry'
};
 
hostapd.enable(options, function(err) {
  // the access point was created 
  console.log(err)
  console.log('Hostapd')
});
```

Got Error
```
{ [Error: Command failed: /bin/sh -c cat <<EOF >wlan0-hostapd.conf && hostapd -B wlan0-hostapd.conf && rm -f wlan0-hostapd.conf
channel=6
driver=rtl871xdrv
hw_mode=g
interface=wlan0
ssid=RaspberryPi
wpa=2
wpa_passphrase=raspberry
]
  killed: false,
  code: 1,
  signal: null,
  cmd: '/bin/sh -c cat <<EOF >wlan0-hostapd.conf && hostapd -B wlan0-hostapd.conf && rm -f wlan0-hostapd.conf\nchannel=6\ndriver=rtl871xdrv\nhw_mode=g\ninterface=wlan0\nssid=RaspberryPi\nwpa=2\nwpa_passphrase=raspberry' }
Hostapd
```

**Comment by snowbreeze** [comment]
Fixed this by removing driver from the options.

**Comment by Noext** [comment]
got the same issue with a rpi3b+ up to date.

I need to run the commande twice to get it working 

> { Error: Command failed: cat <<EOF >wlan0-hostapd.conf && hostapd -B wlan0-hostapd.conf && rm -f wlan0-hostapd.conf
channel=6
hw_mode=g
interface=wlan0
ssid=RaspberryPi
wpa=2
wpa_passphrase=raspberry
    at ChildProcess.exithandler (child_process.js:289:12)
    at ChildProcess.emit (events.js:182:13)
    at maybeClose (internal/child_process.js:961:16)
    at Socket.stream.socket.on (internal/child_process.js:380:11)
    at Socket.emit (events.js:182:13)
    at Pipe._handle.close (net.js:599:12)
  killed: false,
  code: 1,
  signal: null,
  cmd:
   'cat <<EOF >wlan0-hostapd.conf && hostapd -B wlan0-hostapd.conf && rm -f wlan0-hostapd.conf\nchannel=6\nhw_mode=g\ninterface=wlan0\nssid=RaspberryPi\nwpa=2\nwpa_passphrase=raspberry' }

i it seems that if a AP was previously running it fail but even with a disable call before it fail too
