### ISSUE TITLE
how to use wpa_cli.set_network() ?

### ISSUE THREAD

**Issue by Nishanksingla** [bakerface/wireless-tools#20]
I have been trying to use "wpa_cli.set_network(interface, id, variable, value, callback)". 
Below is my code.

```
var wpa_cli = require('wireless-tools/wpa_cli');

 wpa_cli.set_network("wlan0", 0, "ssid", "SuperQuark-Slow", function(err,data) {
            if (err) {
                console.log("set_network ssid");
                console.log(err);
            } else {
                console.log("set_network ssid");
                console.log(data);
                }
});
```

I am getting this error : "[Error: FAIL]". 

Please help me in this.

**Comment by TheMSB** [comment]
If you are still having this problem I would be willing to help you out. Could you post me an output of your ifconfig command?

**Comment by TheMSB** [comment]
Also, have you tried using single quotes?
