### ISSUE TITLE
ifconfig only grabs 4 attributes

### ISSUE THREAD

**Issue by dkran** [bakerface/wireless-tools#28]
Hi, on my system (kali / debian), ifconfig only gets 5 attributes:
- `interface`
- `broadcast`
- `multicast`
- `running`
- `up`

I'd like to submit a pull request to fix them, but I wanted to know if you would consider it and if you're looking for help.  For example, on your `match` for `ipv4_address`, you use `inet addr`.  For this release and ifconfig, it uses simply `inet` for ipv4 and `inet6` for ipv6.  

For MAC address, it uses `ether` (I know it kind of seems unrelated) instead of `HWaddr`.  Right now in my app I'm using other modules and joining the objects together, but I'd like to simplify.  Plus Kali linux is a great use for your module, the control would be great!  

If you're looking for help, I could probably either modify the regexp or throw a couple 'or's in there

Forgot to mention, AWESOME module!

**Comment by gaurav-git** [comment]
This would be a great addition. Also, in the current package the `ifconfig.up` command throws error if netmask and broadcast address is kept empty.
There is no any option to run just `ifconfg eth0 up` or `ifconfig wlan0 up`.
@bakerface It would be great if you can add this feature or ask anyone who is interested to work on this feature.

**Comment by nathanbussey** [comment]
This is an issue for me as well. Going to try and follow @dkran 's info so I can get the ip addresses. But if there are better regex expressions I should be using, then that would be great too.

**Comment by terrytech** [comment]
> This would be a great addition. Also, in the current package the `ifconfig.up` command throws error if netmask and broadcast address is kept empty.
> There is no any option to run just `ifconfg eth0 up` or `ifconfig wlan0 up`.
> @bakerface It would be great if you can add this feature or ask anyone who is interested to work on this feature.

I know this is an old thread, but i just created https://github.com/bakerface/wireless-tools/pull/56 which allows for a simple `ifconfig wlan0 up` etc.
