### ISSUE TITLE
hostapd AP doesn't stay on [RPI3]

### ISSUE THREAD

**Issue by luandro** [bakerface/wireless-tools#32]
I'm trying to broadcast a network from my Raspberry Pi 3 using rasbian.  This seems related to #15 so I followed the advice from @snowbreeze in setting dnsmasq and network interfaces. But as soon as the network begins to be broadcast, Wifi reverts back to connecting to the router.

Do I need to disable this behavior manually some how?

**Comment by kevireilly** [comment]
@luandro the wifi reverts on the pi or on the client attempting to connect? For me, I needed to add something to the `ifconfig` command in #15. Added a comment there.

**Comment by Subh1994** [comment]
@luandro  the wifi coming in your raspberry pi 3 need to be disabled , by using command "sudo service network-manager stop" . By using above command it will disable the wifi and your access point will enable to provide wifi to your client
