### ISSUE TITLE
ifconfig support for Debian stretch

### ISSUE THREAD

**Issue by macmpi** [bakerface/wireless-tools#40]
Hi,
It seems now-stable debian 9.1 "stretch" has slightly changes `ifconfig` report format:
```
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1500
        inet 192.168.1.101  netmask 255.255.255.0  broadcast 192.168.1.255
        ether e8:80:2e:e7:a4:cb  txqueuelen 1000  (Ethernet)
        RX packets 2598  bytes 223207 (217.9 KiB)
        RX errors 0  dropped 12  overruns 0  frame 0
        TX packets 1760  bytes 879290 (858.6 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0
```
Therefore the library does not report correct information anymore (ip address for instance).
Any plan for a fix?
Thanks.

**Comment by macmpi** [comment]
Below is the net-tools notice about the format changes that are now part of net-tools 2.10-alpha in Stretch:

> net-tools (1.60+git20161116.90da8a0-1) unstable; urgency=medium
> After 15 years without upstream development, net-tools is being worked on
> again, fixing many long-standing issues.
> The bad news is that the output of many commands has changed, and it is sure
> to break scripts that relied on parsing it.
> If you have customs scripts that use any of these commands, please make sure
> they still work after this upgrade:
> netstat, ifconfig, ipmaddr, iptunnel, mii-tool, nameif, plipconfig, rarp,
> route, slattach, arp.
> Apologies in advance for the trouble that this may cause, but maintaining a
> separate version of net-tools just to keep the old format is something I am
> not able to do.
> -- Martín Ferrari tincho@debian.org Mon, 26 Dec 2016 05:29:25 +0000

**Comment by bjpirt** [comment]
I've updated the parsing to handle this change in the pull request #41 - would be great if we could get this merged soon as it's causing issues for me right now. Going to npm install from github until then.

I've noticed there are quite a few old pull requests - hopefully this isn't a dead repo as it's a really useful project.

**Comment by peebles** [comment]
Will this change be backward compatible with pre-stretch versions?  I am exploring libs to use for a React UX I need to write, and this lib looks dreamy!  I am not sure what version of Raspbian I'll end up on, and I'd prefer not to worry about that.

In the mean time, can you share your package.json line for pulling in your version of this lib?
