### ISSUE TITLE
UTF8 names are not decoded

### ISSUE THREAD

**Issue by neophob** [bakerface/wireless-tools#43]
If the SSID contains a UTF8 character, the ssid contains not decoded strings like `"TEST\xc3"`

to fix it, I currently use this function

```
function decodeUtf8(string) {
  return Buffer.from(string, 'ascii').toString('utf8');
}
```

however this should be in the library and not in the application

**Comment by 04116** [comment]
use this instead: \t([^\t]+(?=\n))
