### ISSUE TITLE
wpa_cli list_networks not available

### ISSUE THREAD

**Issue by fvisticot** [bakerface/wireless-tools#47]
The wpa_cli module can select a network with the select_network but how to get the list of networks with ids

If i'm correct select_network should set a network id. how to get the list of available network ids ?

**Comment by fvisticot** [comment]
Any update / information ? I really need this information to continue my project. Tx in advance

**Comment by Serveurperso** [comment]
Hello, Same problem here : the list_networks applet from wpa_cli is mandatory to use select_network [id] !!!
Without list_networks, select_network is useless !

multi AP management is mandatory for my robotics projets where I need high reliability (switch to next configured AP if the robot can't reach the cloud).
