### ISSUE TITLE
Open WiFi nw

### ISSUE THREAD

**Issue by szz-dvl** [bakerface/wireless-tools#6]
In order to join open wifi networks I added a bit of code to your 'wpa_supplicant.js' file, changes are the following:

enable function is for me:

``` javascript
function enable(options, callback) {
  var file = options.interface + '-wpa_supplicant.conf';

    if (options.passphrase) {

        var command = 'wpa_passphrase "' + options.ssid + '" "' + options.passphrase
            + '" > ' + file + ' && wpa_supplicant -i ' + options.interface + ' -B -D '
            + options.driver + ' -c ' + file + ' && rm -f ' + file;

    } else {

        fs.writeFileSync(file, 'network={ \n' +
            '\tssid="'+ options.ssid + '"\n' + '\tkey_mgmt=NONE\n'
            + '}\n');

        var command = 'wpa_supplicant -i ' + options.interface + ' -B -D '
            + options.driver + ' -c ' + file + ' && rm -f ' + file;
    }

  return this.exec(command, callback);  
}
```

As you will notice, there is a new dependency in the code, the native 'fs' module. I wasn't able to print the double quotes surrounding the ssid value with echo utility, so to me it is enough, I hope it helps!

szz.

**Comment by luandro** [comment]
Should send a PR with this :+1:

**Comment by tslater** [comment]
This looks pretty old.

**Comment by szz-dvl** [comment]
Hey, it is old, I've been busy thes days, when i get a little bit of time i
will do the PR as you ask ... and I will explain you in detail for what
your code has been used. Thanks and sorry for the delay.

2017-02-14 17:59 GMT+01:00 Tyler Sl8r <notifications@github.com>:

**Comment by mschmidt18** [comment]
I created PR #33 to add this feature. I was able to print the command with the double quotes using printf instead of using the 'fs' module.

**Comment by szz-dvl** [comment]
Hey nice ! thanks for posting this! and nice work with "printf"
