### ISSUE TITLE
Maintenance status?

### ISSUE THREAD

**Issue by meelash** [bakerface/wireless-tools#64]
Hi,

Is there any interest to keep maintaining this software? I see issues and pull requests without responses seen 2016.

If yes please review/merge pull requests or put out a call for another maintainer to take over.

If not, I am applying to have a "community fork" be maintained by the abandonware project:

https://abandonware.github.io/

Relate-to: abandonware/abandonware.github.io#5 Regards

**Comment by bakerface** [comment]
@meelash I added a section to the readme. If you are interesting in maintaining this project, please let me know.
